/*
 * Webshop Service API
 *
 * Webshop services connect Webshop applications to ERP system. The entry point of Webshop API is `/customers/{companyName}/{customerNr}`, which is called by Webshop application whenever a user logs in. If the customer requestedOrderPosition by its number could be found, the response contains a `_links` section, which contains all possible navigations and actions the customer can take.
 *
 * OpenAPI spec version: 2.0-draftAv
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Helpers;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;
using System.Reflection;
using System.Runtime.Versioning;
using System.IO;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace IO.Swagger.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class UtilApiController : ControllerBase
    {
        private readonly Dal _dal;
        private readonly ILogger<UtilApiController> _logger;

        public UtilApiController(Dal dal, ILogger<UtilApiController> logger)
        {
            _dal = dal;
            _logger = logger;
        }
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Public endpoint returns release, build and version information of running service. 
        /// This public endpoint is the only one, that is not protected any security measurement, and can therefore used as health-check by any monitoring application.</remarks>
        /// <response code="200">Successful response provides release information.</response>
        [HttpGet]
        [Route("/apps/prod-webshop-service-app/webshop-service/release")]
        [ValidateModelState]
        [SwaggerOperation("GetReleaseInfo")]
        [SwaggerResponse(statusCode: 200, type: typeof(ReleaseInfo), description: "Successful response provides release information.")]
        
        public virtual IActionResult GetReleaseInfo()
        {
           
                string assemblyVersion = GetType().Assembly.GetName().Version.ToString();

                string packageVersion = Assembly.GetEntryAssembly().GetCustomAttribute<AssemblyInformationalVersionAttribute>().InformationalVersion;

                DateTime releaseDate = Convert.ToDateTime("2020-01-01");

                var filesPath = Directory.GetCurrentDirectory() + "/Resources/";
                if (System.IO.Directory.Exists(filesPath))
                {
                    var path = Path.Combine(filesPath, Path.GetFileName("BuildDate.txt"));
                    releaseDate = Convert.ToDateTime(System.IO.File.ReadAllText(path));
                }
            try
            {
                return new ObjectResult(new ReleaseInfo() { ReleaseBuild = assemblyVersion, ReleaseVersion = packageVersion, ReleaseDate = releaseDate });
            }
            finally
            {
                assemblyVersion = null; packageVersion = null; filesPath = null;
            }
        }

        private static readonly TimeSpan FixAvailabilityCooldown = TimeSpan.FromMinutes(30);
        private static DateTimeOffset? _fixAvailabilityLastRanAt;

        /// <summary>
        /// Executes the FixAvailabilitySlowdown stored procedure to reset the query plan
        /// for the availability procedure when the SQL optimizer produces a bad plan.
        /// Enforces a 30-minute cooldown between executions.
        /// </summary>
        /// <response code="200">Procedure executed successfully.</response>
        /// <response code="429">Cooldown period has not elapsed yet.</response>
        /// <response code="500">Execution failed — check application logs for details.</response>
        [HttpGet]
        [Route("/apps/prod-webshop-service-app/webshop-service/util/fix-availability-slowdown")]
        [SwaggerOperation("FixAvailabilitySlowdown")]
        [SwaggerResponse(statusCode: 200, description: "Procedure executed successfully.")]
        [SwaggerResponse(statusCode: 429, description: "Cooldown period has not elapsed yet.")]
        [SwaggerResponse(statusCode: 500, description: "Execution failed.")]
        public async Task<IActionResult> FixAvailabilitySlowdown()
        {
            if (_fixAvailabilityLastRanAt.HasValue)
            {
                var elapsed = DateTimeOffset.UtcNow - _fixAvailabilityLastRanAt.Value;
                if (elapsed < FixAvailabilityCooldown)
                {
                    var remaining = FixAvailabilityCooldown - elapsed;
                    _logger.LogWarning("UtilApiController: FixAvailabilitySlowdown cooldown active, {Minutes}m {Seconds}s remaining.",
                        (int)remaining.TotalMinutes, remaining.Seconds);
                    return StatusCode(429, new
                    {
                        message = "Cooldown active. Please wait before running this again.",
                        remainingSeconds = (int)remaining.TotalSeconds
                    });
                }
            }

            _logger.LogInformation("UtilApiController: executing FixAvailabilitySlowdown.");
            try
            {
                await _dal.ExecSpAsync("FixAvailabilitySlowdown", new List<Microsoft.Data.SqlClient.SqlParameter>());
                _fixAvailabilityLastRanAt = DateTimeOffset.UtcNow;
                _logger.LogInformation("UtilApiController: FixAvailabilitySlowdown completed successfully.");
                return Ok(new { message = "FixAvailabilitySlowdown executed successfully." });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "UtilApiController: FixAvailabilitySlowdown failed.");
                return StatusCode(500, new { message = "Execution failed. See application logs for details." });
            }
        }
    }
}
