/*
 * Webshop Service API
 *
 * Webshop services connect Webshop applications to ERP system. The entry point of Webshop API is `/customers/{companyName}/{customerNr}`, which is called by Webshop application whenever a user logs in. If the customer requestedOrderPosition by its number could be found, the response contains a `_links` section, which contains all possible navigations and actions the customer can take.
 *
 * OpenAPI spec version: 2.0-draftAv
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ArticleVendor : IEquatable<ArticleVendor>
    { 
        /// <summary>
        /// The vendor id
        /// </summary>
        /// <value>The vendor id</value>
        [DataMember(Name="vendorId")]
        public string VendorId { get; set; }

        /// <summary>
        /// The vendor name
        /// </summary>
        /// <value>The vendor name</value>
        [DataMember(Name="vendorName")]
        public string VendorName { get; set; }

        /// <summary>
        /// The vendor lead time
        /// </summary>
        /// <value>The vendor lead time</value>
        [DataMember(Name="leadTime")]
        public string LeadTime { get; set; }

        /// <summary>
        /// The article id
        /// </summary>
        /// <value>The article id</value>
        [DataMember(Name="articleId")]
        public string ArticleId { get; set; }

        /// <summary>
        /// The external (vendor) article id
        /// </summary>
        /// <value>The external (vendor) article id</value>
        [DataMember(Name="externalArticleId")]
        public string ExternalArticleId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ArticleVendor {\n");
            sb.Append("  VendorId: ").Append(VendorId).Append("\n");
            sb.Append("  VendorName: ").Append(VendorName).Append("\n");
            sb.Append("  LeadTime: ").Append(LeadTime).Append("\n");
            sb.Append("  ArticleId: ").Append(ArticleId).Append("\n");
            sb.Append("  ExternalArticleId: ").Append(ExternalArticleId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ArticleVendor)obj);
        }

        /// <summary>
        /// Returns true if ArticleVendor instances are equal
        /// </summary>
        /// <param name="other">Instance of ArticleVendor to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ArticleVendor other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    VendorId == other.VendorId ||
                    VendorId != null &&
                    VendorId.Equals(other.VendorId)
                ) && 
                (
                    VendorName == other.VendorName ||
                    VendorName != null &&
                    VendorName.Equals(other.VendorName)
                ) && 
                (
                    LeadTime == other.LeadTime ||
                    LeadTime != null &&
                    LeadTime.Equals(other.LeadTime)
                ) && 
                (
                    ArticleId == other.ArticleId ||
                    ArticleId != null &&
                    ArticleId.Equals(other.ArticleId)
                ) && 
                (
                    ExternalArticleId == other.ExternalArticleId ||
                    ExternalArticleId != null &&
                    ExternalArticleId.Equals(other.ExternalArticleId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (VendorId != null)
                    hashCode = hashCode * 59 + VendorId.GetHashCode();
                    if (VendorName != null)
                    hashCode = hashCode * 59 + VendorName.GetHashCode();
                    if (LeadTime != null)
                    hashCode = hashCode * 59 + LeadTime.GetHashCode();
                    if (ArticleId != null)
                    hashCode = hashCode * 59 + ArticleId.GetHashCode();
                    if (ExternalArticleId != null)
                    hashCode = hashCode * 59 + ExternalArticleId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ArticleVendor left, ArticleVendor right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ArticleVendor left, ArticleVendor right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
