/*
 * Webshop Service API
 *
 * Webshop services connect Webshop applications to ERP system. The entry point of Webshop API is `/customers/{companyName}/{customerNr}`, which is called by Webshop application whenever a user logs in. If the customer requestedOrderPosition by its number could be found, the response contains a `_links` section, which contains all possible navigations and actions the customer can take.
 *
 * OpenAPI spec version: 2.0-draftAv
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class OrderProcessStatus : IEquatable<OrderProcessStatus>
    { 
        /// <summary>
        /// The number of the order which the process status will be changed.
        /// </summary>
        /// <value>The number of the order which the process status will be changed.</value>
        [Required]
        [DataMember(Name="orderNr")]
        public string OrderNr { get; set; }

        /// <summary>
        /// The order process status to change to.
        /// </summary>
        /// <value>The order process status to change to.</value>
        [DataMember(Name="processStatus")]
        public string ProcessStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrderProcessStatus {\n");
            sb.Append("  OrderNr: ").Append(OrderNr).Append("\n");
            sb.Append("  ProcessStatus: ").Append(ProcessStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((OrderProcessStatus)obj);
        }

        /// <summary>
        /// Returns true if OrderProcessStatus instances are equal
        /// </summary>
        /// <param name="other">Instance of OrderProcessStatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrderProcessStatus other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    OrderNr == other.OrderNr ||
                    OrderNr != null &&
                    OrderNr.Equals(other.OrderNr)
                ) && 
                (
                    ProcessStatus == other.ProcessStatus ||
                    ProcessStatus != null &&
                    ProcessStatus.Equals(other.ProcessStatus)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (OrderNr != null)
                    hashCode = hashCode * 59 + OrderNr.GetHashCode();
                    if (ProcessStatus != null)
                    hashCode = hashCode * 59 + ProcessStatus.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(OrderProcessStatus left, OrderProcessStatus right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(OrderProcessStatus left, OrderProcessStatus right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
