/*
 * Webshop Service API
 *
 * Webshop services connect Webshop applications to ERP system. The entry point of Webshop API is `/customers/{companyName}/{customerNr}`, which is called by Webshop application whenever a user logs in. If the customer requestedOrderPosition by its number could be found, the response contains a `_links` section, which contains all possible navigations and actions the customer can take.
 *
 * OpenAPI spec version: 2.0-draftAv
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.Diagnostics.CodeAnalysis;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PriceRequestItemForExternalLocationOrdering : IEquatable<PriceRequestItemForExternalLocationOrdering>
    { 
        /// <summary>
        /// The id of the article to get a price for.
        /// </summary>
        /// <value>The id of the article to get a price for.</value>
        [Required]
        [DataMember(Name="articleId")]
        public string ArticleId { get; set; }

        /// <summary>
        /// Requested quantity of article, which need to be greater than zero.
        /// </summary>
        /// <value>Requested quantity of article, which need to be greater than zero.</value>
        [Required]
        [DataMember(Name="quantity")]
        public double? Quantity { get; set; }

        /// <summary>
        /// Gets or Sets BrandId
        /// </summary>
        [DataMember(Name="brandId")]
        public long? BrandId { get; set; }


        /// <summary>
        /// ExternalOrderingLocationId
        /// </summary>
        /// <value>ExternalOrderingLocationId</value>
        [Required]
        [DataMember(Name = "externalOrderingLocationId")]
        public string ExternalOrderingLocationId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PriceRequestItem {\n");
            sb.Append("  ArticleId: ").Append(ArticleId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  BrandId: ").Append(BrandId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PriceRequestItem)obj);
        }

        /// <summary>
        /// Returns true if PriceRequestItem instances are equal
        /// </summary>
        /// <param name="other">Instance of PriceRequestItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PriceRequestItem other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ArticleId == other.ArticleId ||
                    ArticleId != null &&
                    ArticleId.Equals(other.ArticleId)
                ) && 
                (
                    Quantity == other.Quantity ||
                    Quantity != null &&
                    Quantity.Equals(other.Quantity)
                ) && 
                (
                    BrandId == other.BrandId ||
                    BrandId != null &&
                    BrandId.Equals(other.BrandId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ArticleId != null)
                    hashCode = hashCode * 59 + ArticleId.GetHashCode();
                    if (Quantity != null)
                    hashCode = hashCode * 59 + Quantity.GetHashCode();
                    if (BrandId != null)
                    hashCode = hashCode * 59 + BrandId.GetHashCode();
                return hashCode;
            }
        }

        public bool Equals([AllowNull] PriceRequestItemForExternalLocationOrdering other)
        {
            throw new NotImplementedException();
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(PriceRequestItemForExternalLocationOrdering left, PriceRequestItemForExternalLocationOrdering right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PriceRequestItemForExternalLocationOrdering left, PriceRequestItemForExternalLocationOrdering right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
