/*
 * Webshop Service API
 *
 * Webshop services connect Webshop applications to ERP system. The entry point of Webshop API is `/customers/{companyName}/{customerNr}`, which is called by Webshop application whenever a user logs in. If the customer requestedOrderPosition by its number could be found, the response contains a `_links` section, which contains all possible navigations and actions the customer can take.
 *
 * OpenAPI spec version: 2.0-draftAv
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ReturnOrderRequestPosition : IEquatable<ReturnOrderRequestPosition>
    { 
        /// <summary>
        /// Lot id of the source sales order
        /// </summary>
        /// <value>Lot id of the source sales order</value>
        [Required]
        [DataMember(Name="transId")]
        public string TransId { get; set; }

        /// <summary>
        /// Quantity to be returned
        /// </summary>
        /// <value>Quantity to be returned</value>
        [Required]
        [DataMember(Name="quantity")]
        public decimal? Quantity { get; set; }

        /// <summary>
        /// True, if the created return order position should be marked as quarantine
        /// </summary>
        /// <value>True, if the created return order position should be marked as quarantine</value>
        [DataMember(Name="isQuarantine")]
        public bool? IsQuarantine { get; set; }

        /// <summary>
        /// Reason why the item is marked as quarantine. Free Text. Mandatory if isQuarantine is true
        /// </summary>
        /// <value>Reason why the item is marked as quarantine. Free Text. Mandatory if isQuarantine is true</value>
        [DataMember(Name="quarantineReason")]
        public string QuarantineReason { get; set; }

        /// <summary>
        /// Optional return reason code id, if not set default from return order name will be used
        /// </summary>
        /// <value>Optional return reason code id, if not set default from return order name will be used</value>
        [DataMember(Name="returnReasonCodeId")]
        public string ReturnReasonCodeId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReturnOrderRequestPosition {\n");
            sb.Append("  TransId: ").Append(TransId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  IsQuarantine: ").Append(IsQuarantine).Append("\n");
            sb.Append("  QuarantineReason: ").Append(QuarantineReason).Append("\n");
            sb.Append("  ReturnReasonCodeId: ").Append(ReturnReasonCodeId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ReturnOrderRequestPosition)obj);
        }

        /// <summary>
        /// Returns true if ReturnOrderRequestPosition instances are equal
        /// </summary>
        /// <param name="other">Instance of ReturnOrderRequestPosition to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReturnOrderRequestPosition other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    TransId == other.TransId ||
                    TransId != null &&
                    TransId.Equals(other.TransId)
                ) && 
                (
                    Quantity == other.Quantity ||
                    Quantity != null &&
                    Quantity.Equals(other.Quantity)
                ) && 
                (
                    IsQuarantine == other.IsQuarantine ||
                    IsQuarantine != null &&
                    IsQuarantine.Equals(other.IsQuarantine)
                ) && 
                (
                    QuarantineReason == other.QuarantineReason ||
                    QuarantineReason != null &&
                    QuarantineReason.Equals(other.QuarantineReason)
                ) && 
                (
                    ReturnReasonCodeId == other.ReturnReasonCodeId ||
                    ReturnReasonCodeId != null &&
                    ReturnReasonCodeId.Equals(other.ReturnReasonCodeId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (TransId != null)
                    hashCode = hashCode * 59 + TransId.GetHashCode();
                    if (Quantity != null)
                    hashCode = hashCode * 59 + Quantity.GetHashCode();
                    if (IsQuarantine != null)
                    hashCode = hashCode * 59 + IsQuarantine.GetHashCode();
                    if (QuarantineReason != null)
                    hashCode = hashCode * 59 + QuarantineReason.GetHashCode();
                    if (ReturnReasonCodeId != null)
                    hashCode = hashCode * 59 + ReturnReasonCodeId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ReturnOrderRequestPosition left, ReturnOrderRequestPosition right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ReturnOrderRequestPosition left, ReturnOrderRequestPosition right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
