//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavWebServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ConnectIntegration", ConfigurationName="NavWebServiceReference.ConnectIntegration_Port")]
    public interface ConnectIntegration_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ConnectIntegration:CreateConnectOrderInNA" +
            "V", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NavWebServiceReference.CreateConnectOrderInNAV_Result CreateConnectOrderInNAV(NavWebServiceReference.CreateConnectOrderInNAV request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ConnectIntegration:CreateConnectOrderInNA" +
            "V", ReplyAction="*")]
        System.Threading.Tasks.Task<NavWebServiceReference.CreateConnectOrderInNAV_Result> CreateConnectOrderInNAVAsync(NavWebServiceReference.CreateConnectOrderInNAV request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/OrderRequest")]
    public partial class OrderRequest
    {
        
        private OrderRequestConnectWebSalesHeader[] orderRequestConnectWebSalesHeaderField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderRequestConnectWebSalesHeader", Order=0)]
        public OrderRequestConnectWebSalesHeader[] OrderRequestConnectWebSalesHeader
        {
            get
            {
                return this.orderRequestConnectWebSalesHeaderField;
            }
            set
            {
                this.orderRequestConnectWebSalesHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/OrderRequest")]
    public partial class OrderRequestConnectWebSalesHeader
    {
        
        private string customerNrField;
        
        private string branchIdField;
        
        private string sendMethodField;
        
        private bool partialDeliveryField;
        
        private string paymentMethodField;
        
        private string deliveryAddressIdField;
        
        private string pickupBranchIdField;
        
        private string customerRefTextField;
        
        private string messageField;
        
        private bool singleInvoiceField;
        
        private bool completeInvoiceField;
        
        private string personalNumberField;
        
        private string salesOriginField;
        
        private string orderTypeField;
        
        private string courierServiceCodeField;
        
        private string userNameField;
        
        private string emailField;
        
        private items[] itemsField;
        
        public OrderRequestConnectWebSalesHeader()
        {
            this.partialDeliveryField = false;
            this.singleInvoiceField = false;
            this.completeInvoiceField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string customerNr
        {
            get
            {
                return this.customerNrField;
            }
            set
            {
                this.customerNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string branchId
        {
            get
            {
                return this.branchIdField;
            }
            set
            {
                this.branchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sendMethod
        {
            get
            {
                return this.sendMethodField;
            }
            set
            {
                this.sendMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool partialDelivery
        {
            get
            {
                return this.partialDeliveryField;
            }
            set
            {
                this.partialDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string paymentMethod
        {
            get
            {
                return this.paymentMethodField;
            }
            set
            {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string deliveryAddressId
        {
            get
            {
                return this.deliveryAddressIdField;
            }
            set
            {
                this.deliveryAddressIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string pickupBranchId
        {
            get
            {
                return this.pickupBranchIdField;
            }
            set
            {
                this.pickupBranchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string customerRefText
        {
            get
            {
                return this.customerRefTextField;
            }
            set
            {
                this.customerRefTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool singleInvoice
        {
            get
            {
                return this.singleInvoiceField;
            }
            set
            {
                this.singleInvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool completeInvoice
        {
            get
            {
                return this.completeInvoiceField;
            }
            set
            {
                this.completeInvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string personalNumber
        {
            get
            {
                return this.personalNumberField;
            }
            set
            {
                this.personalNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string salesOrigin
        {
            get
            {
                return this.salesOriginField;
            }
            set
            {
                this.salesOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string orderType
        {
            get
            {
                return this.orderTypeField;
            }
            set
            {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string courierServiceCode
        {
            get
            {
                return this.courierServiceCodeField;
            }
            set
            {
                this.courierServiceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("items", Order=17)]
        public items[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/OrderRequest")]
    public partial class items
    {
        
        private string articleIdField;
        
        private decimal quantityField;
        
        private int brandIdField;
        
        private string modelField;
        
        private string brandField;
        
        private string typeField;
        
        private string sourcingTypeField;
        
        private string vendorIdField;
        
        private System.DateTime arrivalTimeField;
        
        private string externalLineNumberField;
        
        private string additionalTextDocField;
        
        private string additionalTextDocPrintersField;
        
        private string registrationDocNrField;
        
        private string priceDiscTypeIdField;
        
        public items()
        {
            this.quantityField = ((decimal)(0.00m));
            this.brandIdField = 0;
            this.arrivalTimeField = new System.DateTime(0);
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string articleId
        {
            get
            {
                return this.articleIdField;
            }
            set
            {
                this.articleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int brandId
        {
            get
            {
                return this.brandIdField;
            }
            set
            {
                this.brandIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string model
        {
            get
            {
                return this.modelField;
            }
            set
            {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string brand
        {
            get
            {
                return this.brandField;
            }
            set
            {
                this.brandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sourcingType
        {
            get
            {
                return this.sourcingTypeField;
            }
            set
            {
                this.sourcingTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string vendorId
        {
            get
            {
                return this.vendorIdField;
            }
            set
            {
                this.vendorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime arrivalTime
        {
            get
            {
                return this.arrivalTimeField;
            }
            set
            {
                this.arrivalTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string externalLineNumber
        {
            get
            {
                return this.externalLineNumberField;
            }
            set
            {
                this.externalLineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string additionalTextDoc
        {
            get
            {
                return this.additionalTextDocField;
            }
            set
            {
                this.additionalTextDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string additionalTextDocPrinters
        {
            get
            {
                return this.additionalTextDocPrintersField;
            }
            set
            {
                this.additionalTextDocPrintersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string registrationDocNr
        {
            get
            {
                return this.registrationDocNrField;
            }
            set
            {
                this.registrationDocNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string priceDiscTypeId
        {
            get
            {
                return this.priceDiscTypeIdField;
            }
            set
            {
                this.priceDiscTypeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/OrderConfirmation")]
    public partial class tourTimeTable
    {
        
        private string tourNameTimeTableField;
        
        private string startTimeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tourNameTimeTable
        {
            get
            {
                return this.tourNameTimeTableField;
            }
            set
            {
                this.tourNameTimeTableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string startTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/OrderConfirmation")]
    public partial class availabilities
    {
        
        private string articleIdField;
        
        private decimal quantityField;
        
        private bool backOrderField;
        
        private System.DateTime cutOffTimeField;
        
        private System.DateTime deliveryTimeField;
        
        private bool immediateDeliveryField;
        
        private string stockWarehouseField;
        
        private string deliveryWarehouseField;
        
        private string sendMethodField;
        
        private int assignmentPriorityField;
        
        private string errorMessageField;
        
        private string tourNameField;
        
        private tourTimeTable[] tourTimeTableField;
        
        public availabilities()
        {
            this.quantityField = ((decimal)(0.00m));
            this.backOrderField = false;
            this.cutOffTimeField = new System.DateTime(0);
            this.deliveryTimeField = new System.DateTime(0);
            this.immediateDeliveryField = false;
            this.assignmentPriorityField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string articleId
        {
            get
            {
                return this.articleIdField;
            }
            set
            {
                this.articleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool backOrder
        {
            get
            {
                return this.backOrderField;
            }
            set
            {
                this.backOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime cutOffTime
        {
            get
            {
                return this.cutOffTimeField;
            }
            set
            {
                this.cutOffTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime deliveryTime
        {
            get
            {
                return this.deliveryTimeField;
            }
            set
            {
                this.deliveryTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool immediateDelivery
        {
            get
            {
                return this.immediateDeliveryField;
            }
            set
            {
                this.immediateDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string stockWarehouse
        {
            get
            {
                return this.stockWarehouseField;
            }
            set
            {
                this.stockWarehouseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string deliveryWarehouse
        {
            get
            {
                return this.deliveryWarehouseField;
            }
            set
            {
                this.deliveryWarehouseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string sendMethod
        {
            get
            {
                return this.sendMethodField;
            }
            set
            {
                this.sendMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int assignmentPriority
        {
            get
            {
                return this.assignmentPriorityField;
            }
            set
            {
                this.assignmentPriorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string tourName
        {
            get
            {
                return this.tourNameField;
            }
            set
            {
                this.tourNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tourTimeTable", Order=12)]
        public tourTimeTable[] tourTimeTable
        {
            get
            {
                return this.tourTimeTableField;
            }
            set
            {
                this.tourTimeTableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/OrderConfirmation")]
    public partial class OrderConfirmationConnectWebSalesHeader
    {
        
        private string orderNrField;
        
        private string axOrderURLField;
        
        private string workIdsField;
        
        private bool allPositionsAvailableField;
        
        private bool creditLimitExceededField;
        
        private availabilities[] availabilitiesField;
        
        public OrderConfirmationConnectWebSalesHeader()
        {
            this.allPositionsAvailableField = false;
            this.creditLimitExceededField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string orderNr
        {
            get
            {
                return this.orderNrField;
            }
            set
            {
                this.orderNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string axOrderURL
        {
            get
            {
                return this.axOrderURLField;
            }
            set
            {
                this.axOrderURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string workIds
        {
            get
            {
                return this.workIdsField;
            }
            set
            {
                this.workIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool allPositionsAvailable
        {
            get
            {
                return this.allPositionsAvailableField;
            }
            set
            {
                this.allPositionsAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool creditLimitExceeded
        {
            get
            {
                return this.creditLimitExceededField;
            }
            set
            {
                this.creditLimitExceededField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("availabilities", Order=5)]
        public availabilities[] availabilities
        {
            get
            {
                return this.availabilitiesField;
            }
            set
            {
                this.availabilitiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/OrderConfirmation")]
    public partial class OrderConfirmation
    {
        
        private OrderConfirmationConnectWebSalesHeader[] orderConfirmationConnectWebSalesHeaderField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderConfirmationConnectWebSalesHeader", Order=0)]
        public OrderConfirmationConnectWebSalesHeader[] OrderConfirmationConnectWebSalesHeader
        {
            get
            {
                return this.orderConfirmationConnectWebSalesHeaderField;
            }
            set
            {
                this.orderConfirmationConnectWebSalesHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateConnectOrderInNAV", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ConnectIntegration", IsWrapped=true)]
    public partial class CreateConnectOrderInNAV
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ConnectIntegration", Order=0)]
        public NavWebServiceReference.OrderRequest importConnectOrderRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ConnectIntegration", Order=1)]
        public NavWebServiceReference.OrderConfirmation exportConnectOrderConfirmation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ConnectIntegration", Order=2)]
        public bool connectOrderInNAVCreated;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ConnectIntegration", Order=3)]
        public string errorMessage;
        
        public CreateConnectOrderInNAV()
        {
        }
        
        public CreateConnectOrderInNAV(NavWebServiceReference.OrderRequest importConnectOrderRequest, NavWebServiceReference.OrderConfirmation exportConnectOrderConfirmation, bool connectOrderInNAVCreated, string errorMessage)
        {
            this.importConnectOrderRequest = importConnectOrderRequest;
            this.exportConnectOrderConfirmation = exportConnectOrderConfirmation;
            this.connectOrderInNAVCreated = connectOrderInNAVCreated;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateConnectOrderInNAV_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ConnectIntegration", IsWrapped=true)]
    public partial class CreateConnectOrderInNAV_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ConnectIntegration", Order=0)]
        public NavWebServiceReference.OrderConfirmation exportConnectOrderConfirmation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ConnectIntegration", Order=1)]
        public bool connectOrderInNAVCreated;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ConnectIntegration", Order=2)]
        public string errorMessage;
        
        public CreateConnectOrderInNAV_Result()
        {
        }
        
        public CreateConnectOrderInNAV_Result(NavWebServiceReference.OrderConfirmation exportConnectOrderConfirmation, bool connectOrderInNAVCreated, string errorMessage)
        {
            this.exportConnectOrderConfirmation = exportConnectOrderConfirmation;
            this.connectOrderInNAVCreated = connectOrderInNAVCreated;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ConnectIntegration_PortChannel : NavWebServiceReference.ConnectIntegration_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ConnectIntegration_PortClient : System.ServiceModel.ClientBase<NavWebServiceReference.ConnectIntegration_Port>, NavWebServiceReference.ConnectIntegration_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConnectIntegration_PortClient() : 
                base(ConnectIntegration_PortClient.GetDefaultBinding(), ConnectIntegration_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ConnectIntegration_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConnectIntegration_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(ConnectIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), ConnectIntegration_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConnectIntegration_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConnectIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConnectIntegration_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConnectIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConnectIntegration_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavWebServiceReference.CreateConnectOrderInNAV_Result NavWebServiceReference.ConnectIntegration_Port.CreateConnectOrderInNAV(NavWebServiceReference.CreateConnectOrderInNAV request)
        {
            return base.Channel.CreateConnectOrderInNAV(request);
        }
        
        public void CreateConnectOrderInNAV(NavWebServiceReference.OrderRequest importConnectOrderRequest, ref NavWebServiceReference.OrderConfirmation exportConnectOrderConfirmation, ref bool connectOrderInNAVCreated, ref string errorMessage)
        {
            NavWebServiceReference.CreateConnectOrderInNAV inValue = new NavWebServiceReference.CreateConnectOrderInNAV();
            inValue.importConnectOrderRequest = importConnectOrderRequest;
            inValue.exportConnectOrderConfirmation = exportConnectOrderConfirmation;
            inValue.connectOrderInNAVCreated = connectOrderInNAVCreated;
            inValue.errorMessage = errorMessage;
            NavWebServiceReference.CreateConnectOrderInNAV_Result retVal = ((NavWebServiceReference.ConnectIntegration_Port)(this)).CreateConnectOrderInNAV(inValue);
            exportConnectOrderConfirmation = retVal.exportConnectOrderConfirmation;
            connectOrderInNAVCreated = retVal.connectOrderInNAVCreated;
            errorMessage = retVal.errorMessage;
        }
        
        public System.Threading.Tasks.Task<NavWebServiceReference.CreateConnectOrderInNAV_Result> CreateConnectOrderInNAVAsync(NavWebServiceReference.CreateConnectOrderInNAV request)
        {
            return base.Channel.CreateConnectOrderInNAVAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConnectIntegration_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConnectIntegration_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.212:7051/DynamicsNAV_3/WS/Wagen International d.o.o/Codeunit/Con" +
                        "nectIntegration");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConnectIntegration_PortClient.GetBindingForEndpoint(EndpointConfiguration.ConnectIntegration_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConnectIntegration_PortClient.GetEndpointAddress(EndpointConfiguration.ConnectIntegration_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            ConnectIntegration_Port,
        }
    }
}
